name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/my-devops-image .
        docker tag your-dockerhub-username/my-devops-image:latest your-dockerhub-username/my-devops-image:${{ github.sha }}
        docker push your-dockerhub-username/my-devops-image:latest
        docker push your-dockerhub-username/my-devops-image:${{ github.sha }}
      

