name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.Amanpass_2003 }}" | docker login -u "${{ secrets.Amanid_2003 }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t Amanid_2003/my-devops-image .
          docker tag Amanid_2003/my-devops-image:latest Amanid_2003/my-devops-image:${{ github.sha }}
          docker push Amanid_2003/my-devops-image:latest
          docker push Amanid_2003/my-devops-image:${{ github.sha }}
